CREATE TABLE "barang" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama" varchar,
  "harga" integer,
  "stok" integer,
  "barang_masuk" timestamp,
  "barang_kadaluarsa" timestamp,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "kategori" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama" varchar,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "kategori_barang" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "barang_id" integer,
  "kategori_id" integer,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

ALTER TABLE "kategori_barang" ADD FOREIGN KEY ("barang_id") REFERENCES "barang" ("id");

ALTER TABLE "kategori_barang" ADD FOREIGN KEY ("kategori_id") REFERENCES "kategori" ("id");
